name: Build/Release FLLUX Desktop

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write # تسمح للـ Workflow بإنشاء Release ورفع الملفات

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false # إذا فشل الماك، لا يتم إلغاء الويندوز واللينكس
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest] # استخدمنا macos-latest لتجنب خطأ التوافق في GitHub

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build/Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          # تجاوز مشكلة توقيع الكود في الماك مؤقتاً للبناء بدون شهادة مطور
          args: "-c.mac.identity=null"
